### ISSUE TITLE
Infinite Scroll + Footer

### ISSUE THREAD

**Issue by bookercodes** [MadRabbit/nikolay.rocks#3]
@MadRabbit. This repo is _awesome_.  Well done mate.

~~I just want to point out a tiny flaw which is that, as the user scrolls down, the site injects new posts and the footer is pushed down.~~

I explain my _issue_ better [below](https://github.com/MadRabbit/nikolay.rocks/issues/3#issuecomment-124467204).

**Comment by kaievns** [comment]
Hey Alex, thanks for the feedback!

Regarding the footer/scroller, thats a feature :) because the posts index is already in memory, we can have an endless scrolling with little overhead. It will eventually stop when you scroll to the very bottom of it

**Comment by bookercodes** [comment]
Mhm. I know the _infinite scroll_ is feature but the "tiny flaw" is that you cannot read the footer text until you scroll to the bottom. This is a [well known UX issue](https://www.google.ca/search?q=infinite+scroll+and+footer&oq=infinite+scroll+and+footer&aqs=chrome.0.69i59j0j69i59j69i61j0l2.2347j0j4&sourceid=chrome&es_sm=93&ie=UTF-8).

In your case, you could move the footer beneath the `aside` column and give it a [fixed position](https://www.google.ca/search?q=fixed+footer&oq=fixed+footer&aqs=chrome..69i57j0l4j69i61.1695j0j7&sourceid=chrome&es_sm=93&ie=UTF-8).

You cold optionally add a ["Load more"](http://uxmovement.com/navigation/infinite-scrolling-best-practices/) button but that is a bit more involved to implement.

**Comment by kaievns** [comment]
Hm, that's a good point, thanks! Ill patch it up shortly

**Comment by bookercodes** [comment]
Thank you for taking on board my feedback :smile:

**Comment by kaievns** [comment]
hey, no problem. thank you for the advice! looks better now
