### ISSUE TITLE
"Keep reading" link does not work

### ISSUE THREAD

**Issue by bookercodes** [MadRabbit/nikolay.rocks#5]
When I click _"Keep reading ->"_ for _any_ article, I am not redirected like I would expect.

I do get an error in the Console, though:

![](http://i.imgur.com/WPXdJ2z.png)

This is Google Chrome where I have some extensions installed that could interfere. I tried this in Internet Explorer where I have no extensions and it does not work there, either.

**Comment by kaievns** [comment]
woops. thanks! all should be fine now :)

**Comment by bookercodes** [comment]
Hehe. I was just browsing your blog and I noticed you fixed it before I got the GitHub notification :stuck_out_tongue:
