### ISSUE TITLE
"Keyboard: Meet the Halmak" post from April incorrectly shows Halmak 2.0 instead of 1.0

### ISSUE THREAD

**Issue by fridgewidget** [MadRabbit/nikolay.rocks#9]
Hi Nikolay, I recently discovered your Halmak keyboard layout project and am following it with interest.

While reading your past posts, I found what appears to be a retrospectively introduced error: Your older "Keyboard: Meet the Halmak" post (<http://nikolay.rocks/2016-04-02-meet-halmak>), which introduced the Halmak 1.0 layout, is now incorrectly showing the newer Halmak 2.0 layout (VLRPZ;) instead. This guess is based on two things:

(1) Your older "Keyboard: Meet the Halmak" post (<http://nikolay.rocks/2016-04-02-meet-halmak>) currently shows a keyboard layout ("screenshot.png") which has the ";" "." and "," punctuation characters in the middle (VLRPZ;). However, your more recent "Keyboard: We've Been Doing It Wrong" post (<http://nikolay.rocks/2016-06-26-we-were-wrong>) indicates that you only later decided to place these punctuation characters in the middle, for Halmak 2.0.

(2) Checking out an earlier revision of the Halmak project (for example, "git checkout 8a835afdc60b82789096c27663410bf4b76dd7e4" from the "halmak" directory) gets a different "screenshot.png", which I'm guessing is the real Halmak 1.0 (FLRWKQ).

Although I realize you're now (understandably) more focused on developing Halmak 2.0 than maintaining the old Halmak 1.0, I still think this issue should be fixed, so people following your posts from beginning to end don't get confused, and to correct the historical record. :-)

**Comment by kaievns** [comment]
Hey there. Thank you for letting me know about the issue. It seems that i've messed up the screenshot refs. I'll patch it up soon!

**Comment by kaievns** [comment]
i think that was resolved a few weeks ago. thanks!
